### ISSUE TITLE
Did you verufy the sollutions?

### ISSUE THREAD

**Issue by reinoud1957** [gfornari/stable-roommates-problem#1]
I try to use your code but I get unexpected results;
example:
	document.getElementById("demo").innerHTML = computeMatches([
    															[5,2,4,1,3],
                                                                [2,4,0,5,3],
                                                                [1,5,0,4,3],
                                                                [4,0,1,2,5],
                                                                [5,0,1,2,3],
                                                                [3,1,4,0,2],

                                                            	]); 

gives no result.

Your test set 

gives 5,4,3,2,1,0 which I do not understand? is that 5-4, 3-2, 1-0?

please can you help me to understand

**Comment by gfornari** [comment]
Hi @reinoud1957, glad you reached out!

The result of `5,4,3,2,1,0` means that the item in position `0` should be matched with the item `5`, the item in position `2` should be matches with the item `4`, and so on. So you end up having the matches: `(0,5)`, `(1,4)`, `(2,3)`.

Regarding your input preferences, if it gives no result (did it return `null`?), then this set of preferences should not allow a _stable_ matching (note that we're looking for _stable_ matchings only). I'll give it a try to check your results 🙂 

Does this answer your questions?

**Comment by reinoud1957** [comment]
Maybe  I will get into it. Thanks for now and I wll let you know.

Met vriendelijke groet,
Reinoud van Mens

________________________________

**Comment by reinoud1957** [comment]
Before i start testing can one assign any set like abc,bca etc or must it be integers and starting with 0?

**Comment by reinoud1957** [comment]
O and gives it all possible matches?

**Comment by gfornari** [comment]
> can one assign any set like abc,bca etc or must it be integers and starting with 0?

All the items are expected to be integers starting from 0. I'll update the README mentioning that, thanks for the hint.

> gives it all possible matches?

No, it gives you only one solution.

**Comment by reinoud1957** [comment]
I have send you an email, did you get it?

**Comment by reinoud1957** [comment]
problems getting php preferences in and pairings out

**Comment by gfornari** [comment]
> I have send you an email, did you get it?

No, I didn't 🤔 

> problems getting php preferences in and pairings out

What do you mean by "php preferences"? Can you share your code so I can reproduce it?

**Comment by reinoud1957** [comment]
?>  /comment: escape php
      		<script src="wp-content/plugins/rvm/srp-js/stable-roommates-algorithm.js"></script>
       
       		<script>
            
     	 		var name = [
                            [2,3,1,5,4],
                            [5,4,3,0,2],
                            [1,3,4,0,5],
                            [4,1,2,5,0],
                            [2,0,1,3,5],
                            [4,0,2,3,1]
                            ];
               
                
				var a = computeMatches([
                            [2,3,1,5,4],
                            [5,4,3,0,2],
                            [1,3,4,0,5],
                            [4,1,2,5,0],
                            [2,0,1,3,5],
                            [4,0,2,3,1]
                            ]);
            
        </script> 	
  
<?php
	
    $js= "<script>document.write(a)</script>"; //I want above javascript variable 'a' value to be store here; **I get a result** :
    echo '<h2> variable = print_r</h2><br>'.$js;
 
 	$var = str_replace ( ',','= ', $js);
   
	echo 'var'. $var; // Outputs 9, the current value of the JS
  	
	$myArray = explode(',', $js); /* gives me array[0] ->1,2,3.. instead of A[]->5, A[1]->2 etc, no array, I can not acces the variables!
and if I replace in computeMatches the matrix by (name) empty array?? 
*/

**Comment by reinoud1957** [comment]
well the code is a bit messy above, but I hope you see what I do.

**Comment by reinoud1957** [comment]
this I send you by mail:
I am working on the execution of tour stable roommate script .
What I am struggeling with, and this has to do with my lack of knowledge of the different languages and maybe you have some suggestions, or even better a working example.

In PHP I have my preference list $preferences and when i do this:

?>
  <body>
    <p id="demo"></p>
    <script src="wp-content/plugins/rvm/srp-js/stable-roommates-algorithm.js"></script>
    <script>
             document.write("<h3>start</h3>");
             var name = [
                            [2,3,1,5,4],
                            [5,4,3,0,2],
                            [1,3,4,0,5],
                            [4,1,2,5,0],
                            [2,0,1,3,5],
                            [4,0,2,3,1]
                            ];
               
               
var a = document.getElementById("demo").innerHTML = computeMatches([
                            [2,3,1,5,4],
                            [5,4,3,0,2],
                            [1,3,4,0,5],
                            [4,1,2,5,0],
                            [2,0,1,3,5],
                            [4,0,2,3,1]
                            ]);
               

                document.write("<h3>finished</h3>");
        </script>
 </body>

<?php

    $variable = "<script>document.write(a)</script>"; //I want above javascript variable 'a' value to be store here
    echo '<h2> output document.write(a) </h2><br>';
   var_dump ($variable);

Output:
Start!
finished

I get : output document.write(a)   string(34) "5,3,4,1,2,0"

So this is fine! But I can not get var name in computeMatches(name)

output: string(34) "undefined"


So maybe you can help me with that, how to get a variable in computematches( var), containing the preference list.

**Comment by gfornari** [comment]
I suggest you to share a formatted and executable code when you share it, it would make the others more willing to help you, you bring them straight to the point, and, ultimately, you more luckily get help 🙂 

That said, as far as I can see, I think you should not use `var`, but `let/const` in your code as the `stable-roommates-algorithm` is implemented with the latter instructions. Since you're evaluating your code javascript code in a browser, how mixing `var` and `let/const` behaves really depends on the browser.

Also, be aware that this algorithm implementation is not intended to be executed in a browser, although possible (with some drawbacks).

Let me know if it solves the issue.

**Comment by reinoud1957** [comment]
No it did not solve it. I am sorry but there is no way to get the front end js output to php variable. Only with the post method, but that is not good because you need to submit. So I stopped trying. Now I am working with [https://github.com/CoeCS/tacklebox](url). But there is an error in the program, which I try to figure out. Before hand it looked so simple. There were 4 algorithms, php, js (yours) , py and r. Java I got working but the webhosting does not allow java to run . Bummer!! Then js but the output can not be used in  further processing, unless in the script. 
R is complete new to me and also not allowed to run on the webhosting server and py is ok but there seems to be an error. The struggling life of an amateur in computer science in a nuttshell. Thank you for our support.
